"""Identifiants et styles partages par l'adaptateur documentaire Qt."""

from PySide6.QtGui import QTextFormat


_MEROPE_PROPERTY_BASE = int(QTextFormat.Property.UserProperty)

# Proprietes de bloc.
BLOCK_KIND_PROPERTY = _MEROPE_PROPERTY_BASE + 1
HEADING_LEVEL_PROPERTY = _MEROPE_PROPERTY_BASE + 2
ALIGNMENT_PROPERTY = _MEROPE_PROPERTY_BASE + 3
LIST_KIND_PROPERTY = _MEROPE_PROPERTY_BASE + 4
RAW_BLOCK_KIND_PROPERTY = _MEROPE_PROPERTY_BASE + 5
RAW_BLOCK_GROUP_PROPERTY = _MEROPE_PROPERTY_BASE + 6

# Proprietes de caracteres. Elles portent la semantique Merope independamment
# du rendu visuel choisi pour le QTextDocument.
BOLD_PROPERTY = _MEROPE_PROPERTY_BASE + 20
ITALIC_PROPERTY = _MEROPE_PROPERTY_BASE + 21
STRIKETHROUGH_PROPERTY = _MEROPE_PROPERTY_BASE + 22
SUPERSCRIPT_PROPERTY = _MEROPE_PROPERTY_BASE + 23
UNDERLINE_PROPERTY = _MEROPE_PROPERTY_BASE + 24

# Proprietes des images. Les attributs documentaires restent distincts des
# dimensions natives de QTextImageFormat, qui ne servent qu'au rendu.
IMAGE_MARKER_PROPERTY = _MEROPE_PROPERTY_BASE + 40
IMAGE_SRC_PROPERTY = _MEROPE_PROPERTY_BASE + 41
IMAGE_ALT_PROPERTY = _MEROPE_PROPERTY_BASE + 42
IMAGE_WIDTH_PROPERTY = _MEROPE_PROPERTY_BASE + 43
IMAGE_HEIGHT_PROPERTY = _MEROPE_PROPERTY_BASE + 44
IMAGE_ALIGN_PROPERTY = _MEROPE_PROPERTY_BASE + 45

# Propriétés des appels de note. L'instance est transitoire et empêche Qt de
# fusionner deux marqueurs adjacents identiques ; elle n'est jamais persistée.
FOOTNOTE_MARKER_PROPERTY = _MEROPE_PROPERTY_BASE + 60
FOOTNOTE_ID_PROPERTY = _MEROPE_PROPERTY_BASE + 61
FOOTNOTE_INSTANCE_PROPERTY = _MEROPE_PROPERTY_BASE + 62

HEADING_POINT_SIZES = {1: 24.0, 2: 20.0, 3: 17.0, 4: 15.0}
BODY_POINT_SIZE = 11.0
BLOCKQUOTE_LEFT_MARGIN = 24.0
